### PR TITLE
Jesse's code and comments

### PR DESCRIPTION
**Pull request by jgibbons94**
I finished my work and commented on what I could see of your work. I hope you don't mind that I changed your file name to identify its author.
--Jesse

### CODE REVIEW

**Comment by hbodenheimer** [comment]
Yeah I don't mind. I am still working on the problems I took. I'm having trouble with some of the logic still but I will hopefully figure it out today. I also started coding the second problem and I think I am almost done with that one, but I will have to upload it to here when I'm at home.

**Comment by jgibbons94** [comment]
Merged. I'll review your code again when it's up.

**Comment by hbodenheimer** [comment]
Candace wants you to review my code and see if you can figure out whats
happening with it. I posted my latest attempt on github.

**Comment by jgibbons94** [comment]
I have work but I'll try to review about 2:00

- Jesse Gibbons


________________________________

**Pull request merged**
